base: 18
cmnd: power on
flag: 0
gpio:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
hostname: tasmota
ipaddress1: 192.168.0.100
ipaddress2: 255.255.255.0
ipaddress3: 192.168.0.1
ledstate: 1
module: 0
name: TasmotaDevice
sleep: 0
webserver: 2
